WIDTH = 1200
HEIGHT = 700
FPS = 60

GAME_TIME = 120

MENU = "MENU"
PLAYING = "PLAYING"
PAUSED = "PAUSED"
GOAL_RESET = "GOAL_RESET"
GAME_OVER = "GAME_OVER"

DIFFICULTY = "NORMAL"

GAME_CONFIG = {
    "EASY": {
        "player_speed": 6,
        "kick_force": 9
    },
    "NORMAL": {
        "player_speed": 5,
        "kick_force": 10
    },
    "HARD": {
        "player_speed": 4,
        "kick_force": 12
    }
}

config = GAME_CONFIG[DIFFICULTY]

GREEN = (30, 160, 60)
WHITE = (255, 255, 255)
BLUE = (50, 80, 255)
RED = (255, 50, 50)
YELLOW = (255, 255, 0)

PLAYER_RADIUS = 20
PLAYER_SPEED = config["player_speed"]
KICK_FORCE = config["kick_force"]

BALL_RADIUS = 10
BALL_FRICTION = 0.98

GOAL_WIDTH = 20
GOAL_HEIGHT = 200

GRID_SIZE = 40
SHOW_GRID = False
GRID_COLOR = (40, 120, 60)

AI_SPEED_PENALTY = 2

AI_KICK_FORCE = 8
PASS_FORCE = 7

CONTROL_DISTANCE_OFFSET = 15
MANUAL_CONTROL_DISTANCE_OFFSET = 20

LOSE_CONTROL_MULTIPLIER = 1.5

STEAL_DISTANCE = 80
STEAL_THRESHOLD = 0.6

RELEASE_COOLDOWN = 250

PASS_BLOCK_DISTANCE = 50

GOAL_RESET_COOLDOWN = 1500

AI_SHOOT_DISTANCE = 320

OPEN_PASS_DISTANCE = 160
OPEN_PASS_Y_OFFSET = 90

SUPPORT_DISTANCE_BEHIND_BALL = 120

DEFENDER_COVER_HOME_WEIGHT = 0.7
DEFENDER_COVER_BALL_WEIGHT = 0.3

CHASE_BALL = 'CHASE_BALL'
ATTACK = 'ATTACK'
RETURN_HOME = 'RETURN_HOME'

TEAM_ATTACK = 'TEAM_ATTACK'
TEAM_DEFEND = 'TEAM_DEFEND'

BUTTON_WIDTH = 220
BUTTON_HEIGHT = 60

MENU_START_BUTTON_Y = HEIGHT // 2 - 40
MENU_QUIT_BUTTON_Y = HEIGHT // 2 + 40

GAME_OVER_RESTART_BUTTON_Y = HEIGHT // 2 + 30
GAME_OVER_QUIT_BUTTON_Y = HEIGHT // 2 + 110